# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/receiverTransmitters/KeyboardTop/KeyboardTop.cache/wt [current_project]
set_property parent.project_path F:/receiverTransmitters/KeyboardTop/KeyboardTop.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/receiverTransmitters/KeyboardTop/KeyboardTop.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/sources_1/new/debouncer.v
  F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/sources_1/new/ssd.v
  F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/sources_1/new/Enabler.v
  F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/sources_1/new/keyboardReceiver.v
  F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/sources_1/new/Top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files F:/receiverTransmitters/KeyboardTop/KeyboardTop.srcs/constrs_1/new/master.xdc]


synth_design -top Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
