# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/receiverTransmitters/receiver/Receiver/Receiver.cache/wt [current_project]
set_property parent.project_path F:/receiverTransmitters/receiver/Receiver/Receiver.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/receiverTransmitters/receiver/Receiver/Receiver.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/receiverTransmitters/receiver/Receiver/Receiver.srcs/sources_1/new/receiver.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/receiverTransmitters/receiver/Receiver/Receiver.srcs/constrs_1/new/Master.xdc
set_property used_in_implementation false [get_files F:/receiverTransmitters/receiver/Receiver/Receiver.srcs/constrs_1/new/Master.xdc]


synth_design -top receiver -part xc7a35tcpg236-1


write_checkpoint -force -noxdef receiver.dcp

catch { report_utilization -file receiver_utilization_synth.rpt -pb receiver_utilization_synth.pb }
