# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/SingleStep/SingleStep.cache/wt [current_project]
set_property parent.project_path F:/SingleStep/SingleStep.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/SingleStep/SingleStep.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/SingleStep/SingleStep.srcs/sources_1/new/debouncer.v
  F:/SingleStep/SingleStep.srcs/sources_1/new/ClockMux.v
  F:/SingleStep/SingleStep.srcs/sources_1/new/PS2Receiver2.v
  F:/SingleStep/SingleStep.srcs/sources_1/new/SingleStepper.v
  F:/SingleStep/SingleStep.srcs/sources_1/new/decoder.v
  F:/SingleStep/SingleStep.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/SingleStep/SingleStep.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files F:/SingleStep/SingleStep.srcs/constrs_1/new/master.xdc]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
